[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dk_event_monitor"
version = "0.1.0"
description = "Draftkings Event Monitor Python package"
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "msgpack",
    "python-dotenv",
    "httpx",
    "websockets",
    "black",
    "playwright",
    "tzlocal",
    "pytest (>=8.4.2,<9.0.0)",
    "pytest-asyncio (>=1.2.0,<2.0.0)"
]
[project.optional-dependencies]
dev = [
    "black",
    "pytest",
    "pytest-asyncio",
]

[project.scripts]
format = "black:main"

[tool.black]
line-length = 80
target-version = ['py312']

[tool.setuptools.packages.find]
where = ["."]
include = ["dk_event_monitor/*"]

[tool.poetry]
package-mode = false
